Modules/EmailManager/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('emailmanager')->name('emailmanager.')->group(function() {
    Route::get('/', 'EmailManagerController@index')->name('index');
    Route::get('/upload-excel-view', 'EmailManagerController@uploadExcelView')->name('uploadExcelView');
    Route::post('/import-recipient-excel', 'EmailManagerController@importRecipientEmail')->name('importRecipientEmail');
});

Modules/EmailManager/Entities/RecipientEmail.php
<?php

namespace Modules\EmailManager\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class RecipientEmail extends Model
{
    use HasFactory;

    protected $fillable = ['batch_no','name','number','email_address','user_id'];

    protected static function newFactory()
    {
        return \Modules\EmailManager\Database\factories\RecipientEmailFactory::new();
    }
}

Modules/EmailManager/Http/Controllers/EmailManagerController.php
<?php

namespace Modules\EmailManager\Http\Controllers;

use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
//use Maatwebsite\Excel\Excel;
use Illuminate\Support\Facades\Log;
use Modules\EmailManager\Entities\RecipientEmail;
use Excel;
use App\Imports\EmailImport;

class EmailManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $recipient_emails = RecipientEmail::all();
        return view('emailmanager::index',compact('recipient_emails'));
    }

    /**
     * @return Application|Factory|View
     */
    public function uploadExcelView(){

        return view('emailmanager::upload_excel_view');
    }

    /**
     * @param Request $request
     * @return string
     */
    public function importRecipientEmail(Request $request){

        try {

            Excel::import(new EmailImport,$request->file);
            return redirect()->route('emailmanager.index')
                ->with('success','Excel Uploaded successfully');
        }catch (Exception $e){

            Log::info('ExcelUpError = '.$e->getMessage());
        }

    }

}

Modules/EmailManager/Resources/views/index.blade.php
@extends('emailmanager::layouts.master')
@section('title','Email Master | List')
@section('content')
    <section class="content">
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        <!-- Default box -->
        <div class="box box-info">
            <div class="box-header with-border">
                <div class="col-md-3">
                    <h3 class="box-title" >Recipients Email List</h3>
                </div>

                <div class="col-md-offset-5 col-md-4">
                    <a href="{{asset('bulk_email_temp.xlsx')}}" class="btn btn-primary pull-right" style="margin-left: 5px;">Download Excel Template</a>
                    <a href="{{route('emailmanager.uploadExcelView')}}" class="btn btn-info pull-right" onclick="">Upload Emails</a>
                </div>
            </div>
            <div class="box-body table-responsive no-padding">
                <div class="col-md-12">
                    <table class="table table-bordered table-hover" id="ID_EmpList_tbl">
                        <thead>
                        <tr>
                            <th >Id</th>
                            <th style="" >Name</th>
                            <th >Number</th>
                            <th >Email Address</th>
                        </tr>
                        </thead>
                        <tbody id="" >
                        @foreach($recipient_emails AS $list)
                            <tr>
                                <td>{{$list->id}}</td>
                                <td>{{$list->name}}</td>
                                <td>{{$list->number}}</td>
                                <td>{{$list->email_address}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.box-body -->

        </div>
        <!-- /.box -->

    </section>
@endsection

Modules/EmailManager/Resources/views/layouts/master.blade.php
@extends('layouts.master')
@section('title','Email Master')

Modules/EmailManager/Resources/views/upload_excel_view.blade.php
@extends('emailmanager::layouts.master')
@section('title','Email Master | List')
@section('content')
    <section class="content">

        <!-- Default box -->
        <form method="post" action="{{route('emailmanager.importRecipientEmail')}}" enctype="multipart/form-data">
            @csrf
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title" >Upload Recipient Emails</h3>
                <div class="box-tools pull-right">
                    <a href="{{route('emailmanager.index')}}" class="btn btn-info btn-sm" data-toggle="tooltip" title="">
                        <i class="icon-backward2"></i> Back
                    </a>
                </div>
            </div>
            <div class="box-body" id="customer_add_view">

                    <div class="row">
                        <div class="col-md-offset-3 col-md-6">
                            <label>Choose Filed Recipient Excel file to upload...</label>
                            <input type="file" name="file" class="form-control">
                        </div>
                    </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="row">

                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success pull-right" ><i class="icon-enter3"></i> Submit</button>

                        <button class="btn btn-danger pull-left" style="margin-right: 5px"><i class="icon-cancel-square"></i> Cancel</button>
                    </div>
                </div>
            </div>
        </div>
        </form>
        <!-- /.box -->

    </section>
@endsection