Modules/EmailScheduler/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('emailscheduler')->name('emailscheduler.')->group(function() {
    Route::get('/', 'EmailSchedulerController@index')->name('index');
    Route::get('/create', 'EmailSchedulerController@create')->name('create');
    Route::post('/store', 'EmailSchedulerController@store')->name('store');
    Route::get('/create', 'EmailSchedulerController@create')->name('create');
});

Modules/EmailScheduler/Entities/EmailScheduler.php
<?php

namespace Modules\EmailScheduler\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class EmailScheduler extends Model
{
    use HasFactory;

    protected $table = "email_scheduler";

    protected $fillable = ['email_alias','email_subject','email_body','attache_file_name','send_date','email_batch_id','is_schedule','user_id'];

    protected static function newFactory()
    {
        return \Modules\EmailScheduler\Database\factories\EmailSchedulerFactory::new();
    }
}

Modules/EmailScheduler/Http/Controllers/EmailSchedulerController.php
<?php

namespace Modules\EmailScheduler\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Modules\EmailScheduler\Entities\EmailScheduler;

class EmailSchedulerController extends Controller
{
    public function __construct()
    {
//        error_reporting(E_ALL ^ E_NOTICE);
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $schedule_emails = EmailScheduler::all();

        return view('emailscheduler::index',compact('schedule_emails'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        $batches_list = DB::table('recipient_emails')->where('user_id',auth()->user()->id)->groupBy('batch_no')->get();
        return view('emailscheduler::add_schedule_view',compact('batches_list'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return JsonResponse
     */
    public function store(Request $request)
    {
        $validateData = Validator::make($request->all(),[
            'email_alias' => 'required',
            'email_subject' => 'required',
            'email_body' => 'required',
            'send_date' => 'required',
            'email_batches' => 'required'
        ]);

        if ($validateData->fails()) {
            return response()->json([
                'status'   => false,
                'message'  => $validateData->getMessageBag()
            ],401);
        }
        $attach_name = "";
        if($request->file()) {
            $fileName = time().'_'.$request->email_attach->getClientOriginalName();
            $filePath = $request->file('email_attach')->storeAs('uploads', $fileName, 'public');

            $attach_name = '/storage/' . $filePath;
        }


        $data = [
            'email_alias' => $request->email_alias,
            'email_subject' => $request->email_subject,
            'email_body' => $request->email_body,
            'attache_file_name' => $attach_name,
            'send_date' => $request->send_date,
            'email_batch_id' => json_encode($request->email_batches),
            'user_id' => auth()->user()->id,
        ];
        $res = EmailScheduler::create($data);

        if($res){

            $resp_msg = ['status' => true,'message' => 'Your schedule successfully added.'];
            return response()->json($resp_msg,200);
        }
    }


    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('emailscheduler::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('emailscheduler::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Modules/EmailScheduler/Resources/views/add_schedule_view.blade.php
@extends('emailmanager::layouts.master')
@section('title','Email Master | List')
@section('content')
    <section class="content">

        <!-- Default box -->
        <form method="post" action="{{route('emailscheduler.store')}}" enctype="multipart/form-data" id="schedule-form">
            @csrf
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title" >Add New Schedule</h3>
                <div class="box-tools pull-right">
                    <a href="{{route('emailscheduler.index')}}" class="btn btn-info btn-sm" data-toggle="tooltip" title="">
                        <i class="icon-backward2"></i> Back
                    </a>
                </div>
            </div>
            <div class="box-body" id="customer_add_view">

                    <div class="col-md-offset-3 col-md-6">
                        <div class="form-group">
                            <label>Email Alias</label>
                            <input type="text" name="email_alias" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Email Subject</label>
                            <input type="text" name="email_subject" class="form-control">
                        </div>
                        <div class="form-group" id="email_body_container">
                            <label>Email Body</label>
                            <textarea class="form-control" name="email_body" id="email_body"></textarea>
{{--                            <span id="word_count"></span>--}}
                            <span id="word_left"></span>
                        </div>
                        <div class="form-group">
                            <label>Attachment</label>
                            <input type="file" name="email_attach" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Send Date</label>
                            <input type="datetime-local" name="send_date" class="form-control" value="@php echo date('Y-m-d\TH:i'); @endphp">
                        </div>
                        <div class="form-group">
                            <label>Select Batches</label>
                            <select name="email_batches[]" class="form-control" multiple>
                                @foreach($batches_list AS $bList)
                                    <option value="{{$bList->batch_no}}">{{$bList->batch_no}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="row">

                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success pull-right" ><i class="icon-enter3"></i> Submit</button>

                        <button class="btn btn-danger pull-left" style="margin-right: 5px"><i class="icon-cancel-square"></i> Cancel</button>
                    </div>
                </div>
            </div>
        </div>
        </form>
        <!-- /.box -->

    </section>

    <script>
        var wordLimit = 5000;
        var words = 0;
        var jqContainer = $("#email_body_container");
        var jqElt = $("#email_body");

        function charLimit()
        {
            var words = 0;
            var wordmatch = jqElt.val().match(/[^\s]+\s+/g);
            words = wordmatch?wordmatch.length:0;

            if (words > wordLimit) {
                var trimmed = jqElt.val().split(/(?=[^\s]\s+)/, wordLimit).join("");
                var lastChar = jqElt.val()[trimmed.length];
                jqElt.val(trimmed + lastChar);
            }
            // $('#word_count', jqContainer).text(words);
            $('#word_left', jqContainer).text(Math.max(wordLimit-words, 0));
        }
        $(document).ready(function () {
            jqElt.on("keyup", charLimit);
            charLimit();

            $(document).on('submit', '#schedule-form', function(event){
                event.preventDefault();
                var form = $(this);
                $.ajax({
                    url: form.attr('action'),
                    type: form.attr('method'),
                    data:new FormData(this),
                    contentType:false,
                    processData:false,
                    success:function(data)
                    {
                        $('#schedule-form')[0].reset();
                        location.reload();

                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        if(typeof jqXHR.responseJSON.message == "undefined"){
                            $('#schedule-form')[0].reset();
                            location.reload();
                        }
                        var errors = jqXHR.responseJSON.message;


                        var errorList = "";

                        $.each(errors, function (i, error) {
                            errorList +=  error ;
                        })

                        errorList +=""

                        alert(errorList);
                    }
                });
            });
        })

    </script>
@endsection

Modules/EmailScheduler/Resources/views/index.blade.php
@extends('emailscheduler::layouts.master')

@section('title','Email Scheduler | List')
@section('content')
    <section class="content">
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
    @endif
    <!-- Default box -->
        <div class="box box-info">
            <div class="box-header with-border">
                <div class="col-md-3">
                    <h3 class="box-title" >Recipients Email List</h3>
                </div>

                <div class="col-md-offset-5 col-md-4">
{{--                    <a href="{{asset('bulk_email_temp.xlsx')}}" class="btn btn-primary pull-right" style="margin-left: 5px;">Download Excel Template</a>--}}
                    <a href="{{route('emailscheduler.create')}}" class="btn btn-info pull-right" onclick="">Add New Schedule</a>
                </div>
            </div>
            <div class="box-body table-responsive no-padding">
                <div class="col-md-12">
                    <table class="table table-bordered table-hover" id="ID_EmpList_tbl">
                        <thead>
                        <tr>
                            <th >Id</th>
                            <th style="" >Email Alias</th>
                            <th >Subject</th>
                            <th >Send Date</th>
                        </tr>
                        </thead>
                        <tbody id="" >
                        @foreach($schedule_emails AS $list)
                            <tr>
                                <td>{{$list->id}}</td>
                                <td>{{$list->email_alias}}</td>
                                <td>{{$list->email_subject}}</td>
                                <td>{{$list->send_date}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.box-body -->

        </div>
        <!-- /.box -->

    </section>
@endsection

Modules/EmailScheduler/Resources/views/layouts/master.blade.php
@extends('layouts.master')
@section('title','Email Scheduler')